sudo: required
language: clojure

addons:
  postgresql: "9.3"

services:
  - postgresql

before_install:
  - sudo apt-get install graphviz
  - cd aipal-db

install:
  - sudo pip install ansible==1.9.1

before_script:
  - psql --file=../env/local/db-server/dev.sql 

script:
 - lein run 'postgresql://aipal_adm:aipal-adm@127.0.0.1:5432/aipal' -u aipal_user --clear -t
 - cd ../db-docs
 - generate-schemadocs.sh


